/**
 * bip370 — PSBTv2 data structure library
 *
 * Subpath imports (recommended for tree-shaking):
 *   import { Updater }               from 'bip370/roles';
 *   import { WithSerialization }     from 'bip370/features';
 *   import { InputField }            from 'bip370/fields';
 *   import { keyFromType }           from 'bip370/utils';
 *   import { ValidationErrorContainer } from 'bip370/errors';
 *
 * Or import everything from the root for convenience:
 *   import { PSBTv2Builder }         from 'bip370';
 */
import { Extractor as PsbtRoles } from './roles/extractor';
export declare const PSBTv2Builder: {
    new (...args: any[]): {
        extractTransactionBytes(this: {
            combine(psbts: ({
                _globalMap: Map<string, Uint8Array>;
                _inputMaps: Map<string, Uint8Array>[];
                _outputMaps: Map<string, Uint8Array>[];
                setGlobal(type: number, value: Uint8Array, keyData?: Uint8Array): void;
                getGlobal(type: number, keyData?: Uint8Array): Uint8Array | undefined;
                deleteGlobal(type: number, keyData?: Uint8Array): boolean;
                setInput(index: number, type: number, value: Uint8Array, keyData?: Uint8Array): void;
                setInputByKey(index: number, key: string, value: Uint8Array): void;
                getInput(index: number, type: number, keyData?: Uint8Array): Uint8Array | undefined;
                deleteInput(index: number, type: number, keyData?: Uint8Array): boolean;
                setOutput(index: number, type: number, value: Uint8Array, keyData?: Uint8Array): void;
                setOutputByKey(index: number, key: string, value: Uint8Array): void;
                getOutput(index: number, type: number, keyData?: Uint8Array): Uint8Array | undefined;
                deleteOutput(index: number, type: number, keyData?: Uint8Array): boolean;
                updateGlobalCounts(): void;
                loadGlobalMap(pairs: Map<string, Uint8Array>): void;
                get globalMap(): ReadonlyMap<string, Uint8Array>;
                get inputMaps(): readonly ReadonlyMap<string, Uint8Array>[];
                get outputMaps(): readonly ReadonlyMap<string, Uint8Array>[];
                get inputCount(): number;
                get outputCount(): number;
                get version(): number;
                get txVersion(): number;
                set txVersion(version: number);
                get fallbackLockTime(): number | undefined;
                set fallbackLockTime(lockTime: number);
                get modifiableFlags(): number | undefined;
                set modifiableFlags(flags: number);
                clearModifiableFlags(): void;
                get inputsModifiable(): boolean;
                get outputsModifiable(): boolean;
                get hasSighashSingle(): boolean;
                clone(): /*elided*/ any;
                _pushInputMap(map: Map<string, Uint8Array>): number;
                _pushOutputMap(map: Map<string, Uint8Array>): number;
                addRawInput(map: Map<string, Uint8Array>): number;
                addRawOutput(map: Map<string, Uint8Array>): number;
                removeInput(index: number): /*elided*/ any;
                removeOutput(index: number): /*elided*/ any;
                validate(): import("./errors.js").ValidationErrorContainer | undefined;
                validateOutputs(errorContainer: import("./errors.js").ValidationErrorContainer): void;
                validateInputs(errorContainer: import("./errors.js").ValidationErrorContainer): void;
                validateGlobalFields(errorContainer: import("./errors.js").ValidationErrorContainer): void;
                computeLockTime(): number;
                computeLockTimeForMaps(maps: Map<string, Uint8Array>[]): number | null;
                inputHasSignature(map: Map<string, Uint8Array>): boolean;
                getInputsOfType(index: number, type: number): Array<{
                    keyData: Uint8Array;
                    value: Uint8Array;
                }>;
                hasInputOfType(index: number, type: number): boolean;
                deleteInputsOfType(index: number, type: number): number;
                getOutputsOfType(index: number, type: number): Array<{
                    keyData: Uint8Array;
                    value: Uint8Array;
                }>;
            } & {
                toBuffer(): Uint8Array;
                toBase64(): string;
                toHex(): string;
                byteLength(): number;
                _globalMap: Map<string, Uint8Array>;
                _inputMaps: Map<string, Uint8Array>[];
                _outputMaps: Map<string, Uint8Array>[];
                setGlobal(type: number, value: Uint8Array, keyData?: Uint8Array): void;
                getGlobal(type: number, keyData?: Uint8Array): Uint8Array | undefined;
                deleteGlobal(type: number, keyData?: Uint8Array): boolean;
                setInput(index: number, type: number, value: Uint8Array, keyData?: Uint8Array): void;
                setInputByKey(index: number, key: string, value: Uint8Array): void;
                getInput(index: number, type: number, keyData?: Uint8Array): Uint8Array | undefined;
                deleteInput(index: number, type: number, keyData?: Uint8Array): boolean;
                setOutput(index: number, type: number, value: Uint8Array, keyData?: Uint8Array): void;
                setOutputByKey(index: number, key: string, value: Uint8Array): void;
                getOutput(index: number, type: number, keyData?: Uint8Array): Uint8Array | undefined;
                deleteOutput(index: number, type: number, keyData?: Uint8Array): boolean;
                updateGlobalCounts(): void;
                loadGlobalMap(pairs: Map<string, Uint8Array>): void;
                get globalMap(): ReadonlyMap<string, Uint8Array>;
                get inputMaps(): readonly ReadonlyMap<string, Uint8Array>[];
                get outputMaps(): readonly ReadonlyMap<string, Uint8Array>[];
                get inputCount(): number;
                get outputCount(): number;
                get version(): number;
                get txVersion(): number;
                set txVersion(version: number);
                get fallbackLockTime(): number | undefined;
                set fallbackLockTime(lockTime: number);
                get modifiableFlags(): number | undefined;
                set modifiableFlags(flags: number);
                clearModifiableFlags(): void;
                get inputsModifiable(): boolean;
                get outputsModifiable(): boolean;
                get hasSighashSingle(): boolean;
                clone(): /*elided*/ any;
                _pushInputMap(map: Map<string, Uint8Array>): number;
                _pushOutputMap(map: Map<string, Uint8Array>): number;
                addRawInput(map: Map<string, Uint8Array>): number;
                addRawOutput(map: Map<string, Uint8Array>): number;
                removeInput(index: number): /*elided*/ any;
                removeOutput(index: number): /*elided*/ any;
                validate(): import("./errors.js").ValidationErrorContainer | undefined;
                validateOutputs(errorContainer: import("./errors.js").ValidationErrorContainer): void;
                validateInputs(errorContainer: import("./errors.js").ValidationErrorContainer): void;
                validateGlobalFields(errorContainer: import("./errors.js").ValidationErrorContainer): void;
                computeLockTime(): number;
                computeLockTimeForMaps(maps: Map<string, Uint8Array>[]): number | null;
                inputHasSignature(map: Map<string, Uint8Array>): boolean;
                getInputsOfType(index: number, type: number): Array<{
                    keyData: Uint8Array;
                    value: Uint8Array;
                }>;
                hasInputOfType(index: number, type: number): boolean;
                deleteInputsOfType(index: number, type: number): number;
                getOutputsOfType(index: number, type: number): Array<{
                    keyData: Uint8Array;
                    value: Uint8Array;
                }>;
            } & PsbtRoles & import("./psbtv2.js").PsbtV2Base)[]): /*elided*/ any;
            mergeInputMaps(target: Map<string, Uint8Array>, source: ReadonlyMap<string, Uint8Array>): void;
            mergeOutputMaps(target: Map<string, Uint8Array>, source: ReadonlyMap<string, Uint8Array>): void;
            _globalMap: Map<string, Uint8Array>;
            _inputMaps: Map<string, Uint8Array>[];
            _outputMaps: Map<string, Uint8Array>[];
            setGlobal(type: number, value: Uint8Array, keyData?: Uint8Array): void;
            getGlobal(type: number, keyData?: Uint8Array): Uint8Array | undefined;
            deleteGlobal(type: number, keyData?: Uint8Array): boolean;
            setInput(index: number, type: number, value: Uint8Array, keyData?: Uint8Array): void;
            setInputByKey(index: number, key: string, value: Uint8Array): void;
            getInput(index: number, type: number, keyData?: Uint8Array): Uint8Array | undefined;
            deleteInput(index: number, type: number, keyData?: Uint8Array): boolean;
            setOutput(index: number, type: number, value: Uint8Array, keyData?: Uint8Array): void;
            setOutputByKey(index: number, key: string, value: Uint8Array): void;
            getOutput(index: number, type: number, keyData?: Uint8Array): Uint8Array | undefined;
            deleteOutput(index: number, type: number, keyData?: Uint8Array): boolean;
            updateGlobalCounts(): void;
            loadGlobalMap(pairs: Map<string, Uint8Array>): void;
            get globalMap(): ReadonlyMap<string, Uint8Array>;
            get inputMaps(): readonly ReadonlyMap<string, Uint8Array>[];
            get outputMaps(): readonly ReadonlyMap<string, Uint8Array>[];
            get inputCount(): number;
            get outputCount(): number;
            get version(): number;
            get txVersion(): number;
            set txVersion(version: number);
            get fallbackLockTime(): number | undefined;
            set fallbackLockTime(lockTime: number);
            get modifiableFlags(): number | undefined;
            set modifiableFlags(flags: number);
            clearModifiableFlags(): void;
            get inputsModifiable(): boolean;
            get outputsModifiable(): boolean;
            get hasSighashSingle(): boolean;
            clone(): /*elided*/ any;
            _pushInputMap(map: Map<string, Uint8Array>): number;
            _pushOutputMap(map: Map<string, Uint8Array>): number;
            addRawInput(map: Map<string, Uint8Array>): number;
            addRawOutput(map: Map<string, Uint8Array>): number;
            removeInput(index: number): /*elided*/ any;
            removeOutput(index: number): /*elided*/ any;
            validate(): import("./errors.js").ValidationErrorContainer | undefined;
            validateOutputs(errorContainer: import("./errors.js").ValidationErrorContainer): void;
            validateInputs(errorContainer: import("./errors.js").ValidationErrorContainer): void;
            validateGlobalFields(errorContainer: import("./errors.js").ValidationErrorContainer): void;
            computeLockTime(): number;
            computeLockTimeForMaps(maps: Map<string, Uint8Array>[]): number | null;
            inputHasSignature(map: Map<string, Uint8Array>): boolean;
            getInputsOfType(index: number, type: number): Array<{
                keyData: Uint8Array;
                value: Uint8Array;
            }>;
            hasInputOfType(index: number, type: number): boolean;
            deleteInputsOfType(index: number, type: number): number;
            getOutputsOfType(index: number, type: number): Array<{
                keyData: Uint8Array;
                value: Uint8Array;
            }>;
        } & {
            _globalMap: Map<string, Uint8Array>;
            _inputMaps: Map<string, Uint8Array>[];
            _outputMaps: Map<string, Uint8Array>[];
            setGlobal(type: number, value: Uint8Array, keyData?: Uint8Array): void;
            getGlobal(type: number, keyData?: Uint8Array): Uint8Array | undefined;
            deleteGlobal(type: number, keyData?: Uint8Array): boolean;
            setInput(index: number, type: number, value: Uint8Array, keyData?: Uint8Array): void;
            setInputByKey(index: number, key: string, value: Uint8Array): void;
            getInput(index: number, type: number, keyData?: Uint8Array): Uint8Array | undefined;
            deleteInput(index: number, type: number, keyData?: Uint8Array): boolean;
            setOutput(index: number, type: number, value: Uint8Array, keyData?: Uint8Array): void;
            setOutputByKey(index: number, key: string, value: Uint8Array): void;
            getOutput(index: number, type: number, keyData?: Uint8Array): Uint8Array | undefined;
            deleteOutput(index: number, type: number, keyData?: Uint8Array): boolean;
            updateGlobalCounts(): void;
            loadGlobalMap(pairs: Map<string, Uint8Array>): void;
            get globalMap(): ReadonlyMap<string, Uint8Array>;
            get inputMaps(): readonly ReadonlyMap<string, Uint8Array>[];
            get outputMaps(): readonly ReadonlyMap<string, Uint8Array>[];
            get inputCount(): number;
            get outputCount(): number;
            get version(): number;
            get txVersion(): number;
            set txVersion(version: number);
            get fallbackLockTime(): number | undefined;
            set fallbackLockTime(lockTime: number);
            get modifiableFlags(): number | undefined;
            set modifiableFlags(flags: number);
            clearModifiableFlags(): void;
            get inputsModifiable(): boolean;
            get outputsModifiable(): boolean;
            get hasSighashSingle(): boolean;
            clone(): /*elided*/ any;
            _pushInputMap(map: Map<string, Uint8Array>): number;
            _pushOutputMap(map: Map<string, Uint8Array>): number;
            addRawInput(map: Map<string, Uint8Array>): number;
            addRawOutput(map: Map<string, Uint8Array>): number;
            removeInput(index: number): /*elided*/ any;
            removeOutput(index: number): /*elided*/ any;
            validate(): import("./errors.js").ValidationErrorContainer | undefined;
            validateOutputs(errorContainer: import("./errors.js").ValidationErrorContainer): void;
            validateInputs(errorContainer: import("./errors.js").ValidationErrorContainer): void;
            validateGlobalFields(errorContainer: import("./errors.js").ValidationErrorContainer): void;
            computeLockTime(): number;
            computeLockTimeForMaps(maps: Map<string, Uint8Array>[]): number | null;
            inputHasSignature(map: Map<string, Uint8Array>): boolean;
            getInputsOfType(index: number, type: number): Array<{
                keyData: Uint8Array;
                value: Uint8Array;
            }>;
            hasInputOfType(index: number, type: number): boolean;
            deleteInputsOfType(index: number, type: number): number;
            getOutputsOfType(index: number, type: number): Array<{
                keyData: Uint8Array;
                value: Uint8Array;
            }>;
        } & {
            toBuffer(): Uint8Array;
            toBase64(): string;
            toHex(): string;
            byteLength(): number;
            _globalMap: Map<string, Uint8Array>;
            _inputMaps: Map<string, Uint8Array>[];
            _outputMaps: Map<string, Uint8Array>[];
            setGlobal(type: number, value: Uint8Array, keyData?: Uint8Array): void;
            getGlobal(type: number, keyData?: Uint8Array): Uint8Array | undefined;
            deleteGlobal(type: number, keyData?: Uint8Array): boolean;
            setInput(index: number, type: number, value: Uint8Array, keyData?: Uint8Array): void;
            setInputByKey(index: number, key: string, value: Uint8Array): void;
            getInput(index: number, type: number, keyData?: Uint8Array): Uint8Array | undefined;
            deleteInput(index: number, type: number, keyData?: Uint8Array): boolean;
            setOutput(index: number, type: number, value: Uint8Array, keyData?: Uint8Array): void;
            setOutputByKey(index: number, key: string, value: Uint8Array): void;
            getOutput(index: number, type: number, keyData?: Uint8Array): Uint8Array | undefined;
            deleteOutput(index: number, type: number, keyData?: Uint8Array): boolean;
            updateGlobalCounts(): void;
            loadGlobalMap(pairs: Map<string, Uint8Array>): void;
            get globalMap(): ReadonlyMap<string, Uint8Array>;
            get inputMaps(): readonly ReadonlyMap<string, Uint8Array>[];
            get outputMaps(): readonly ReadonlyMap<string, Uint8Array>[];
            get inputCount(): number;
            get outputCount(): number;
            get version(): number;
            get txVersion(): number;
            set txVersion(version: number);
            get fallbackLockTime(): number | undefined;
            set fallbackLockTime(lockTime: number);
            get modifiableFlags(): number | undefined;
            set modifiableFlags(flags: number);
            clearModifiableFlags(): void;
            get inputsModifiable(): boolean;
            get outputsModifiable(): boolean;
            get hasSighashSingle(): boolean;
            clone(): /*elided*/ any;
            _pushInputMap(map: Map<string, Uint8Array>): number;
            _pushOutputMap(map: Map<string, Uint8Array>): number;
            addRawInput(map: Map<string, Uint8Array>): number;
            addRawOutput(map: Map<string, Uint8Array>): number;
            removeInput(index: number): /*elided*/ any;
            removeOutput(index: number): /*elided*/ any;
            validate(): import("./errors.js").ValidationErrorContainer | undefined;
            validateOutputs(errorContainer: import("./errors.js").ValidationErrorContainer): void;
            validateInputs(errorContainer: import("./errors.js").ValidationErrorContainer): void;
            validateGlobalFields(errorContainer: import("./errors.js").ValidationErrorContainer): void;
            computeLockTime(): number;
            computeLockTimeForMaps(maps: Map<string, Uint8Array>[]): number | null;
            inputHasSignature(map: Map<string, Uint8Array>): boolean;
            getInputsOfType(index: number, type: number): Array<{
                keyData: Uint8Array;
                value: Uint8Array;
            }>;
            hasInputOfType(index: number, type: number): boolean;
            deleteInputsOfType(index: number, type: number): number;
            getOutputsOfType(index: number, type: number): Array<{
                keyData: Uint8Array;
                value: Uint8Array;
            }>;
        } & PsbtRoles & import("./psbtv2.js").PsbtV2Base, allowIncomplete?: boolean): Uint8Array;
        _globalMap: Map<string, Uint8Array>;
        _inputMaps: Map<string, Uint8Array>[];
        _outputMaps: Map<string, Uint8Array>[];
        setGlobal(type: number, value: Uint8Array, keyData?: Uint8Array): void;
        getGlobal(type: number, keyData?: Uint8Array): Uint8Array | undefined;
        deleteGlobal(type: number, keyData?: Uint8Array): boolean;
        setInput(index: number, type: number, value: Uint8Array, keyData?: Uint8Array): void;
        setInputByKey(index: number, key: string, value: Uint8Array): void;
        getInput(index: number, type: number, keyData?: Uint8Array): Uint8Array | undefined;
        deleteInput(index: number, type: number, keyData?: Uint8Array): boolean;
        setOutput(index: number, type: number, value: Uint8Array, keyData?: Uint8Array): void;
        setOutputByKey(index: number, key: string, value: Uint8Array): void;
        getOutput(index: number, type: number, keyData?: Uint8Array): Uint8Array | undefined;
        deleteOutput(index: number, type: number, keyData?: Uint8Array): boolean;
        updateGlobalCounts(): void;
        loadGlobalMap(pairs: Map<string, Uint8Array>): void;
        get globalMap(): ReadonlyMap<string, Uint8Array>;
        get inputMaps(): readonly ReadonlyMap<string, Uint8Array>[];
        get outputMaps(): readonly ReadonlyMap<string, Uint8Array>[];
        get inputCount(): number;
        get outputCount(): number;
        get version(): number;
        get txVersion(): number;
        set txVersion(version: number);
        get fallbackLockTime(): number | undefined;
        set fallbackLockTime(lockTime: number);
        get modifiableFlags(): number | undefined;
        set modifiableFlags(flags: number);
        clearModifiableFlags(): void;
        get inputsModifiable(): boolean;
        get outputsModifiable(): boolean;
        get hasSighashSingle(): boolean;
        clone(): /*elided*/ any;
        _pushInputMap(map: Map<string, Uint8Array>): number;
        _pushOutputMap(map: Map<string, Uint8Array>): number;
        addRawInput(map: Map<string, Uint8Array>): number;
        addRawOutput(map: Map<string, Uint8Array>): number;
        removeInput(index: number): /*elided*/ any;
        removeOutput(index: number): /*elided*/ any;
        validate(): import("./errors.js").ValidationErrorContainer | undefined;
        validateOutputs(errorContainer: import("./errors.js").ValidationErrorContainer): void;
        validateInputs(errorContainer: import("./errors.js").ValidationErrorContainer): void;
        validateGlobalFields(errorContainer: import("./errors.js").ValidationErrorContainer): void;
        computeLockTime(): number;
        computeLockTimeForMaps(maps: Map<string, Uint8Array>[]): number | null;
        inputHasSignature(map: Map<string, Uint8Array>): boolean;
        getInputsOfType(index: number, type: number): Array<{
            keyData: Uint8Array;
            value: Uint8Array;
        }>;
        hasInputOfType(index: number, type: number): boolean;
        deleteInputsOfType(index: number, type: number): number;
        getOutputsOfType(index: number, type: number): Array<{
            keyData: Uint8Array;
            value: Uint8Array;
        }>;
    };
} & {
    new (...args: any[]): {
        combine(psbts: ({
            _globalMap: Map<string, Uint8Array>;
            _inputMaps: Map<string, Uint8Array>[];
            _outputMaps: Map<string, Uint8Array>[];
            setGlobal(type: number, value: Uint8Array, keyData?: Uint8Array): void;
            getGlobal(type: number, keyData?: Uint8Array): Uint8Array | undefined;
            deleteGlobal(type: number, keyData?: Uint8Array): boolean;
            setInput(index: number, type: number, value: Uint8Array, keyData?: Uint8Array): void;
            setInputByKey(index: number, key: string, value: Uint8Array): void;
            getInput(index: number, type: number, keyData?: Uint8Array): Uint8Array | undefined;
            deleteInput(index: number, type: number, keyData?: Uint8Array): boolean;
            setOutput(index: number, type: number, value: Uint8Array, keyData?: Uint8Array): void;
            setOutputByKey(index: number, key: string, value: Uint8Array): void;
            getOutput(index: number, type: number, keyData?: Uint8Array): Uint8Array | undefined;
            deleteOutput(index: number, type: number, keyData?: Uint8Array): boolean;
            updateGlobalCounts(): void;
            loadGlobalMap(pairs: Map<string, Uint8Array>): void;
            get globalMap(): ReadonlyMap<string, Uint8Array>;
            get inputMaps(): readonly ReadonlyMap<string, Uint8Array>[];
            get outputMaps(): readonly ReadonlyMap<string, Uint8Array>[];
            get inputCount(): number;
            get outputCount(): number;
            get version(): number;
            get txVersion(): number;
            set txVersion(version: number);
            get fallbackLockTime(): number | undefined;
            set fallbackLockTime(lockTime: number);
            get modifiableFlags(): number | undefined;
            set modifiableFlags(flags: number);
            clearModifiableFlags(): void;
            get inputsModifiable(): boolean;
            get outputsModifiable(): boolean;
            get hasSighashSingle(): boolean;
            clone(): /*elided*/ any;
            _pushInputMap(map: Map<string, Uint8Array>): number;
            _pushOutputMap(map: Map<string, Uint8Array>): number;
            addRawInput(map: Map<string, Uint8Array>): number;
            addRawOutput(map: Map<string, Uint8Array>): number;
            removeInput(index: number): /*elided*/ any;
            removeOutput(index: number): /*elided*/ any;
            validate(): import("./errors.js").ValidationErrorContainer | undefined;
            validateOutputs(errorContainer: import("./errors.js").ValidationErrorContainer): void;
            validateInputs(errorContainer: import("./errors.js").ValidationErrorContainer): void;
            validateGlobalFields(errorContainer: import("./errors.js").ValidationErrorContainer): void;
            computeLockTime(): number;
            computeLockTimeForMaps(maps: Map<string, Uint8Array>[]): number | null;
            inputHasSignature(map: Map<string, Uint8Array>): boolean;
            getInputsOfType(index: number, type: number): Array<{
                keyData: Uint8Array;
                value: Uint8Array;
            }>;
            hasInputOfType(index: number, type: number): boolean;
            deleteInputsOfType(index: number, type: number): number;
            getOutputsOfType(index: number, type: number): Array<{
                keyData: Uint8Array;
                value: Uint8Array;
            }>;
        } & {
            toBuffer(): Uint8Array;
            toBase64(): string;
            toHex(): string;
            byteLength(): number;
            _globalMap: Map<string, Uint8Array>;
            _inputMaps: Map<string, Uint8Array>[];
            _outputMaps: Map<string, Uint8Array>[];
            setGlobal(type: number, value: Uint8Array, keyData?: Uint8Array): void;
            getGlobal(type: number, keyData?: Uint8Array): Uint8Array | undefined;
            deleteGlobal(type: number, keyData?: Uint8Array): boolean;
            setInput(index: number, type: number, value: Uint8Array, keyData?: Uint8Array): void;
            setInputByKey(index: number, key: string, value: Uint8Array): void;
            getInput(index: number, type: number, keyData?: Uint8Array): Uint8Array | undefined;
            deleteInput(index: number, type: number, keyData?: Uint8Array): boolean;
            setOutput(index: number, type: number, value: Uint8Array, keyData?: Uint8Array): void;
            setOutputByKey(index: number, key: string, value: Uint8Array): void;
            getOutput(index: number, type: number, keyData?: Uint8Array): Uint8Array | undefined;
            deleteOutput(index: number, type: number, keyData?: Uint8Array): boolean;
            updateGlobalCounts(): void;
            loadGlobalMap(pairs: Map<string, Uint8Array>): void;
            get globalMap(): ReadonlyMap<string, Uint8Array>;
            get inputMaps(): readonly ReadonlyMap<string, Uint8Array>[];
            get outputMaps(): readonly ReadonlyMap<string, Uint8Array>[];
            get inputCount(): number;
            get outputCount(): number;
            get version(): number;
            get txVersion(): number;
            set txVersion(version: number);
            get fallbackLockTime(): number | undefined;
            set fallbackLockTime(lockTime: number);
            get modifiableFlags(): number | undefined;
            set modifiableFlags(flags: number);
            clearModifiableFlags(): void;
            get inputsModifiable(): boolean;
            get outputsModifiable(): boolean;
            get hasSighashSingle(): boolean;
            clone(): /*elided*/ any;
            _pushInputMap(map: Map<string, Uint8Array>): number;
            _pushOutputMap(map: Map<string, Uint8Array>): number;
            addRawInput(map: Map<string, Uint8Array>): number;
            addRawOutput(map: Map<string, Uint8Array>): number;
            removeInput(index: number): /*elided*/ any;
            removeOutput(index: number): /*elided*/ any;
            validate(): import("./errors.js").ValidationErrorContainer | undefined;
            validateOutputs(errorContainer: import("./errors.js").ValidationErrorContainer): void;
            validateInputs(errorContainer: import("./errors.js").ValidationErrorContainer): void;
            validateGlobalFields(errorContainer: import("./errors.js").ValidationErrorContainer): void;
            computeLockTime(): number;
            computeLockTimeForMaps(maps: Map<string, Uint8Array>[]): number | null;
            inputHasSignature(map: Map<string, Uint8Array>): boolean;
            getInputsOfType(index: number, type: number): Array<{
                keyData: Uint8Array;
                value: Uint8Array;
            }>;
            hasInputOfType(index: number, type: number): boolean;
            deleteInputsOfType(index: number, type: number): number;
            getOutputsOfType(index: number, type: number): Array<{
                keyData: Uint8Array;
                value: Uint8Array;
            }>;
        } & PsbtRoles & import("./psbtv2.js").PsbtV2Base)[]): /*elided*/ any;
        mergeInputMaps(target: Map<string, Uint8Array>, source: ReadonlyMap<string, Uint8Array>): void;
        mergeOutputMaps(target: Map<string, Uint8Array>, source: ReadonlyMap<string, Uint8Array>): void;
        _globalMap: Map<string, Uint8Array>;
        _inputMaps: Map<string, Uint8Array>[];
        _outputMaps: Map<string, Uint8Array>[];
        setGlobal(type: number, value: Uint8Array, keyData?: Uint8Array): void;
        getGlobal(type: number, keyData?: Uint8Array): Uint8Array | undefined;
        deleteGlobal(type: number, keyData?: Uint8Array): boolean;
        setInput(index: number, type: number, value: Uint8Array, keyData?: Uint8Array): void;
        setInputByKey(index: number, key: string, value: Uint8Array): void;
        getInput(index: number, type: number, keyData?: Uint8Array): Uint8Array | undefined;
        deleteInput(index: number, type: number, keyData?: Uint8Array): boolean;
        setOutput(index: number, type: number, value: Uint8Array, keyData?: Uint8Array): void;
        setOutputByKey(index: number, key: string, value: Uint8Array): void;
        getOutput(index: number, type: number, keyData?: Uint8Array): Uint8Array | undefined;
        deleteOutput(index: number, type: number, keyData?: Uint8Array): boolean;
        updateGlobalCounts(): void;
        loadGlobalMap(pairs: Map<string, Uint8Array>): void;
        get globalMap(): ReadonlyMap<string, Uint8Array>;
        get inputMaps(): readonly ReadonlyMap<string, Uint8Array>[];
        get outputMaps(): readonly ReadonlyMap<string, Uint8Array>[];
        get inputCount(): number;
        get outputCount(): number;
        get version(): number;
        get txVersion(): number;
        set txVersion(version: number);
        get fallbackLockTime(): number | undefined;
        set fallbackLockTime(lockTime: number);
        get modifiableFlags(): number | undefined;
        set modifiableFlags(flags: number);
        clearModifiableFlags(): void;
        get inputsModifiable(): boolean;
        get outputsModifiable(): boolean;
        get hasSighashSingle(): boolean;
        clone(): /*elided*/ any;
        _pushInputMap(map: Map<string, Uint8Array>): number;
        _pushOutputMap(map: Map<string, Uint8Array>): number;
        addRawInput(map: Map<string, Uint8Array>): number;
        addRawOutput(map: Map<string, Uint8Array>): number;
        removeInput(index: number): /*elided*/ any;
        removeOutput(index: number): /*elided*/ any;
        validate(): import("./errors.js").ValidationErrorContainer | undefined;
        validateOutputs(errorContainer: import("./errors.js").ValidationErrorContainer): void;
        validateInputs(errorContainer: import("./errors.js").ValidationErrorContainer): void;
        validateGlobalFields(errorContainer: import("./errors.js").ValidationErrorContainer): void;
        computeLockTime(): number;
        computeLockTimeForMaps(maps: Map<string, Uint8Array>[]): number | null;
        inputHasSignature(map: Map<string, Uint8Array>): boolean;
        getInputsOfType(index: number, type: number): Array<{
            keyData: Uint8Array;
            value: Uint8Array;
        }>;
        hasInputOfType(index: number, type: number): boolean;
        deleteInputsOfType(index: number, type: number): number;
        getOutputsOfType(index: number, type: number): Array<{
            keyData: Uint8Array;
            value: Uint8Array;
        }>;
    };
} & {
    new (...args: any[]): {
        _globalMap: Map<string, Uint8Array>;
        _inputMaps: Map<string, Uint8Array>[];
        _outputMaps: Map<string, Uint8Array>[];
        setGlobal(type: number, value: Uint8Array, keyData?: Uint8Array): void;
        getGlobal(type: number, keyData?: Uint8Array): Uint8Array | undefined;
        deleteGlobal(type: number, keyData?: Uint8Array): boolean;
        setInput(index: number, type: number, value: Uint8Array, keyData?: Uint8Array): void;
        setInputByKey(index: number, key: string, value: Uint8Array): void;
        getInput(index: number, type: number, keyData?: Uint8Array): Uint8Array | undefined;
        deleteInput(index: number, type: number, keyData?: Uint8Array): boolean;
        setOutput(index: number, type: number, value: Uint8Array, keyData?: Uint8Array): void;
        setOutputByKey(index: number, key: string, value: Uint8Array): void;
        getOutput(index: number, type: number, keyData?: Uint8Array): Uint8Array | undefined;
        deleteOutput(index: number, type: number, keyData?: Uint8Array): boolean;
        updateGlobalCounts(): void;
        loadGlobalMap(pairs: Map<string, Uint8Array>): void;
        get globalMap(): ReadonlyMap<string, Uint8Array>;
        get inputMaps(): readonly ReadonlyMap<string, Uint8Array>[];
        get outputMaps(): readonly ReadonlyMap<string, Uint8Array>[];
        get inputCount(): number;
        get outputCount(): number;
        get version(): number;
        get txVersion(): number;
        set txVersion(version: number);
        get fallbackLockTime(): number | undefined;
        set fallbackLockTime(lockTime: number);
        get modifiableFlags(): number | undefined;
        set modifiableFlags(flags: number);
        clearModifiableFlags(): void;
        get inputsModifiable(): boolean;
        get outputsModifiable(): boolean;
        get hasSighashSingle(): boolean;
        clone(): /*elided*/ any;
        _pushInputMap(map: Map<string, Uint8Array>): number;
        _pushOutputMap(map: Map<string, Uint8Array>): number;
        addRawInput(map: Map<string, Uint8Array>): number;
        addRawOutput(map: Map<string, Uint8Array>): number;
        removeInput(index: number): /*elided*/ any;
        removeOutput(index: number): /*elided*/ any;
        validate(): import("./errors.js").ValidationErrorContainer | undefined;
        validateOutputs(errorContainer: import("./errors.js").ValidationErrorContainer): void;
        validateInputs(errorContainer: import("./errors.js").ValidationErrorContainer): void;
        validateGlobalFields(errorContainer: import("./errors.js").ValidationErrorContainer): void;
        computeLockTime(): number;
        computeLockTimeForMaps(maps: Map<string, Uint8Array>[]): number | null;
        inputHasSignature(map: Map<string, Uint8Array>): boolean;
        getInputsOfType(index: number, type: number): Array<{
            keyData: Uint8Array;
            value: Uint8Array;
        }>;
        hasInputOfType(index: number, type: number): boolean;
        deleteInputsOfType(index: number, type: number): number;
        getOutputsOfType(index: number, type: number): Array<{
            keyData: Uint8Array;
            value: Uint8Array;
        }>;
    };
    fromBuffer<TThis extends import("./features/helper.js").MixinConstructorHelper>(this: TThis, buffer: Uint8Array): InstanceType<TThis>;
    fromBase64<TThis extends import("./features/helper.js").MixinConstructorHelper>(this: TThis, data: string): InstanceType<TThis>;
    fromHex<TThis extends import("./features/helper.js").MixinConstructorHelper>(this: TThis, data: string): InstanceType<TThis>;
} & {
    new (...args: any[]): {
        toBuffer(): Uint8Array;
        toBase64(): string;
        toHex(): string;
        byteLength(): number;
        _globalMap: Map<string, Uint8Array>;
        _inputMaps: Map<string, Uint8Array>[];
        _outputMaps: Map<string, Uint8Array>[];
        setGlobal(type: number, value: Uint8Array, keyData?: Uint8Array): void;
        getGlobal(type: number, keyData?: Uint8Array): Uint8Array | undefined;
        deleteGlobal(type: number, keyData?: Uint8Array): boolean;
        setInput(index: number, type: number, value: Uint8Array, keyData?: Uint8Array): void;
        setInputByKey(index: number, key: string, value: Uint8Array): void;
        getInput(index: number, type: number, keyData?: Uint8Array): Uint8Array | undefined;
        deleteInput(index: number, type: number, keyData?: Uint8Array): boolean;
        setOutput(index: number, type: number, value: Uint8Array, keyData?: Uint8Array): void;
        setOutputByKey(index: number, key: string, value: Uint8Array): void;
        getOutput(index: number, type: number, keyData?: Uint8Array): Uint8Array | undefined;
        deleteOutput(index: number, type: number, keyData?: Uint8Array): boolean;
        updateGlobalCounts(): void;
        loadGlobalMap(pairs: Map<string, Uint8Array>): void;
        get globalMap(): ReadonlyMap<string, Uint8Array>;
        get inputMaps(): readonly ReadonlyMap<string, Uint8Array>[];
        get outputMaps(): readonly ReadonlyMap<string, Uint8Array>[];
        get inputCount(): number;
        get outputCount(): number;
        get version(): number;
        get txVersion(): number;
        set txVersion(version: number);
        get fallbackLockTime(): number | undefined;
        set fallbackLockTime(lockTime: number);
        get modifiableFlags(): number | undefined;
        set modifiableFlags(flags: number);
        clearModifiableFlags(): void;
        get inputsModifiable(): boolean;
        get outputsModifiable(): boolean;
        get hasSighashSingle(): boolean;
        clone(): /*elided*/ any;
        _pushInputMap(map: Map<string, Uint8Array>): number;
        _pushOutputMap(map: Map<string, Uint8Array>): number;
        addRawInput(map: Map<string, Uint8Array>): number;
        addRawOutput(map: Map<string, Uint8Array>): number;
        removeInput(index: number): /*elided*/ any;
        removeOutput(index: number): /*elided*/ any;
        validate(): import("./errors.js").ValidationErrorContainer | undefined;
        validateOutputs(errorContainer: import("./errors.js").ValidationErrorContainer): void;
        validateInputs(errorContainer: import("./errors.js").ValidationErrorContainer): void;
        validateGlobalFields(errorContainer: import("./errors.js").ValidationErrorContainer): void;
        computeLockTime(): number;
        computeLockTimeForMaps(maps: Map<string, Uint8Array>[]): number | null;
        inputHasSignature(map: Map<string, Uint8Array>): boolean;
        getInputsOfType(index: number, type: number): Array<{
            keyData: Uint8Array;
            value: Uint8Array;
        }>;
        hasInputOfType(index: number, type: number): boolean;
        deleteInputsOfType(index: number, type: number): number;
        getOutputsOfType(index: number, type: number): Array<{
            keyData: Uint8Array;
            value: Uint8Array;
        }>;
    };
} & typeof PsbtRoles;
export { PsbtV2Base } from './psbtv2.js';
export { SIGHASH_TYPES, MODIFIABLE_FLAGS, type SighashType, type ModifiableFlagsType, } from './types.js';
